### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by nocomp** [cclabsInc/RFCrack#16]
hi,
i wanted to give a try to rfcrack, but i am facing an issue when i want to replay

nocomp@P0wnB0x:~/tools/sdr/RFCrack$ python RFCrack.py -i -F 433985000
Traceback (most recent call last):
  File "RFCrack.py", line 201, in <module>
    attacks.replayLiveCapture(d, args.rolling_code, rf_settings)
  File "/home/nocomp/tools/sdr/RFCrack/src/attacks.py", line 44, in replayLiveCapture
    replay_capture, signal_strength = tools.capturePayload(d,rolling_code, rf_settings)
  File "/home/nocomp/tools/sdr/RFCrack/src/RFFunctions.py", line 21, in capturePayload
    signal_strength= 0 - ord(str(d.getRSSI()))
  File "/home/nocomp/.local/lib/python2.7/site-packages/future/types/newstr.py", line 104, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbe in position 0: ordinal not in range(128)
nocomp@P0wnB0x:~/tools/sdr/RFCrack$ 

any idea what can be wrong?
thx for helping

**Comment by cclabsInc** [comment]
Not offhand, I would try again perhaps in a location with less RF activity it might be picking up something random it can't parse from something else and crashing. Or you could try opening the code and looking at where its decoding that data and maybe adding some error handling to pass that error through.. I will be updating RFCrack when they release official Python3 libraries for RF.. Currently there are only python2 ones.

**Comment by cclabsInc** [comment]
signal_strength= 0 - ord(str(d.getRSSI()))
looks like it might be in this line
maybe comment that line out if its not being used in anything.. or put a try catch around it

**Comment by cclabsInc** [comment]
Hunted down where this is used and I think i know what the issue is.. Please try replacing the code in RFFunctions at line 17 like the following and let me know if it works.. If it does fix the issue I will fix it in the code base!! use proper indentation from the image attached.. when I save this it takes away the indentation apparently.. So make sure its proper indentation for python. 

**From:** 

while True:
        try:
            y, z = d.RFrecv()
            capture = y.encode('hex')
                signal_strength= 0 - ord(str(d.getRSSI()))
        except ChipconUsbTimeoutException:
            pass

**To:** 

while True:
        try:
            y, z = d.RFrecv()
            capture = y.encode('hex')
            try:
                signal_strength= 0 - ord(str(d.getRSSI()))
            except:
                signal_strength = 0
                pass
        except ChipconUsbTimeoutException:
            pass

Let me know if that fixes the issue.. Essentially you just adding error checking around the setting of signal strength and if it gets something funny it just accepts the error and sets the signal to 0 rather then crashing. 

![image](https://user-images.githubusercontent.com/33992409/89955418-d1158c00-dbe7-11ea-8300-c72d95f693bd.png)

**Comment by nocomp** [comment]
hi,
code modification worked like a charm, no more error when launching.
I get an error once it receive a signal, once i clic on keyfob, i get this error:
nocomp@P0wnB0x:~/tools/sdr/RFCrack$ python RFCrack.py -i -F 433985000
Traceback (most recent call last):
  File "RFCrack.py", line 201, in <module>
    attacks.replayLiveCapture(d, args.rolling_code, rf_settings)
  File "/home/nocomp/tools/sdr/RFCrack/src/attacks.py", line 43, in replayLiveCapture
    replay_capture, signal_strength = tools.capturePayload(d,rolling_code, rf_settings)
  File "/home/nocomp/tools/sdr/RFCrack/src/RFFunctions.py", line 46, in capturePayload
    print "SIGNAL STRENGTH: " + str(signal_strength)
UnboundLocalError: local variable 'signal_strength' referenced before assignment
nocomp@P0wnB0x:~/tools/sdr/RFCrack$ 


any idea? 
thxx for your support!

**Comment by cclabsInc** [comment]
Yea so its saying "referenced before assignment"  Which is going to mean there is some order of operations issue int he code by setting it that way.   If I have a chance I will give it a try this weekend and see if I can sus out what that is, might require some kind of global assignment to a default value...    Right now i am buried is course dev for blockchain and need to stay on task to keep up with the timeline.. but I will try to check it this weekend quickly..

**Comment by nocomp** [comment]
hi @cclabsInc ,
hope your are doin ok, did you had the chance to give it a look?
i am discovering your great yt channel, many thanks for all these great tuts!
best regards

**Comment by cclabsInc** [comment]
Oh yea let me take a look at that for you today.. I just finished out the other course I was creating yestaurday.. So I should have a little time.. I will implement that new code fix today and test it to see where that unbound variable error is popping up from..

**Comment by cclabsInc** [comment]
Took a look at that.. Cant really install it on my box since I don't have python2 on here and not about to mess up all of my enviorment.   But it looks like signal_strength is not being set prior to that call.. possibly because of scope with it being set in that exception.  So just set a default value up top under the other variable definitions like: 
capture = ""
roll_captures = []
signal_strength = 0  <---  Just add it here like that.. This way there is always a default value. 

That should probably fix it since at least it will have a value by default...  Hopefully the python3 libraries come out for this soon and I can update things.. Makes no sense to maintain a python2 version.

**Comment by cclabsInc** [comment]
Being updated to python3 next month..
